CREATE TABLE IF NOT EXISTS t_task_plan (
    task_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
    task_name VARCHAR(100) NOT NULL COMMENT '任务名称',
    task_type VARCHAR(50) NOT NULL COMMENT '任务类型：MANUAL/AUTO',
    period VARCHAR(50) DEFAULT NULL COMMENT '任务周期',
    start_time DATETIME NOT NULL COMMENT '任务开始时间',
    end_time DATETIME NOT NULL COMMENT '任务结束时间',
    satellite_id BIGINT NOT NULL COMMENT '卫星ID',
    station_id BIGINT NOT NULL COMMENT '站址ID',
    device_id BIGINT DEFAULT NULL COMMENT '设备ID',
    param_config TEXT COMMENT '任务参数JSON',
    execute_status VARCHAR(20) DEFAULT 'WAITING' COMMENT '执行状态：WAITING/RUNNING/FINISHED/CANCELLED',
    conflict_status CHAR(1) DEFAULT '0' COMMENT '冲突状态：0无冲突 1有冲突',
    conflict_reason VARCHAR(500) DEFAULT NULL COMMENT '冲突原因',
    create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (task_id),
    KEY idx_task_time (start_time, end_time),
    KEY idx_task_station (station_id),
    KEY idx_task_satellite (satellite_id),
    KEY idx_task_device (device_id),
    KEY idx_task_status (execute_status),
    KEY idx_task_conflict (conflict_status)
) COMMENT='任务计划表';
