CREATE TABLE IF NOT EXISTS t_device_control_log (
    control_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '控制ID',
    device_id BIGINT DEFAULT NULL COMMENT '设备ID',
    device_code VARCHAR(64) NOT NULL COMMENT '设备编号',
    command_type VARCHAR(50) NOT NULL COMMENT '命令类型',
    command_key VARCHAR(50) DEFAULT NULL COMMENT '协议KEY',
    command_content TEXT COMMENT '命令内容JSON',
    cmd_code VARCHAR(20) DEFAULT NULL COMMENT '下发命令码',
    frame_hex TEXT COMMENT '下发帧HEX',
    ack_cmd VARCHAR(20) DEFAULT NULL COMMENT '应答命令码',
    ack_status VARCHAR(50) DEFAULT NULL COMMENT 'ACK状态',
    ack_content TEXT COMMENT 'ACK内容JSON',
    send_status VARCHAR(20) DEFAULT 'WAITING' COMMENT '发送状态：WAITING/SUCCESS/FAILED/TIMEOUT',
    send_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
    ack_time DATETIME DEFAULT NULL COMMENT '响应时间',
    operator VARCHAR(64) DEFAULT '' COMMENT '操作人',
    error_msg VARCHAR(500) DEFAULT NULL COMMENT '错误信息',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (control_id),
    KEY idx_device_code (device_code),
    KEY idx_command_type (command_type),
    KEY idx_send_time (send_time),
    KEY idx_send_status (send_status)
) COMMENT='设备控制日志表';
